
#include <CoreFoundation/CFString.h>

extern "C" {

typedef struct OpaqueLSSharedFileListRef*  LSSharedFileListRef;
typedef struct OpaqueLSSharedFileListItemRef*  LSSharedFileListItemRef;

extern CFStringRef kLSSharedFileListFavoriteVolumes;
extern CFStringRef kLSSharedFileListFavoriteItems;
extern CFStringRef kLSSharedFileListRecentApplicationItems;
extern CFStringRef kLSSharedFileListRecentDocumentItems;
extern CFStringRef kLSSharedFileListRecentServerItems;
extern CFStringRef kLSSharedFileListSessionLoginItems;
extern CFStringRef kLSSharedFileListGlobalLoginItems;
extern CFStringRef kLSSharedFileListRecentItemsMaxAmount;
extern CFStringRef kLSSharedFileListVolumesComputerVisible;
extern CFStringRef kLSSharedFileListVolumesIDiskVisible;
extern CFStringRef kLSSharedFileListVolumesNetworkVisible;
extern LSSharedFileListItemRef kLSSharedFileListItemBeforeFirst;
extern LSSharedFileListItemRef kLSSharedFileListItemLast;
extern CFStringRef kLSSharedFileListItemHidden;
extern CFStringRef kLSSharedFileListLoginItemHidden;

}

// Undocumented
CF_EXPORT const CFStringRef kLSSharedFileListItemIsComputer;
CF_EXPORT const CFStringRef kLSSharedFileListItemIsEjectableVolume;
CF_EXPORT const CFStringRef kLSSharedFileListItemIsIDisk;
CF_EXPORT const CFStringRef kLSSharedFileListItemIsMeetingRoom;
CF_EXPORT const CFStringRef kLSSharedFileListItemIsNetwork;
CF_EXPORT const CFStringRef kLSSharedFileListItemIsRemoteDisc;
CF_EXPORT const CFStringRef kLSSharedFileListItemLocked;
CF_EXPORT const CFStringRef kLSSharedFileListItemTargetIsDirectory;
CF_EXPORT const CFStringRef kLSSharedFileListItemTargetIsVolume;
CF_EXPORT const CFStringRef kLSSharedFileListItemTargetName;
CF_EXPORT const CFStringRef kLSSharedFileListSavedSearchesItems;
CF_EXPORT const CFStringRef kLSSharedFileListSharePoints;
CF_EXPORT const CFStringRef kLSSharedFileListSpecialItemIdentifier;
